services:
  location-service:
    build:
      context: .
    image: location-service:0.1
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  redis:
    image: redis